# Generated by Django 3.1.6 on 2021-03-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='werb',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
