# Generated by Django 3.1.6 on 2021-04-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wooordd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
