# Generated by Django 3.1.6 on 2021-04-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_delete_wooordd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
