# Generated by Django 3.1.6 on 2021-04-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ide',
            field=models.IntegerField(default=0),
        ),
    ]
